apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 3
  template:
    metadata:
      name: my-first-pod
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx-container
          image: alaa942/nginx-test
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi"
              